### ISSUE TITLE
Documentation#: include linting to project

### ISSUE THREAD

**Issue by kingan1** [mtkumar123/CSC510_Project_LectureAid#36]
Using black and flake8 code checkers, reformat code and add requirement to build.

**Comment by kingan1** [comment]
Discuss how we want to add this to project, who fixes files, etc. (Required for project 1 rubric)

**Comment by kingan1** [comment]
See .txt files in https://github.com/mtkumar123/CSC510_Project_LectureAid/tree/lint

**Comment by mtkumar123** [comment]
Completed please check lint branch

**Comment by kingan1** [comment]
Closed Lint merged.
